### ISSUE TITLE
Issuer Details Screen

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-iOS#16]
We want to have a modal dialogue that shows additional information about the issuer. 

<img width="320" alt="screen shot 2016-12-21 at 11 09 23 am" src="https://cloud.githubusercontent.com/assets/547866/21400567/fcb1faca-c76d-11e6-88bd-b826a14f53c2.png">

View in [web](https://zpl.io/Z1PDvGo) or [zeplin](zpl://screen?pid=5858222061e610633e76d6a5&sid=585a049624f3080711e9c2e0)

Open questions before implementation:
- [ ] What information do we want to include here?

Changes to make:
- [ ] In the [Issuer screen](zpl://screen?pid=5858222061e610633e76d6a5&sid=585826098560f09263cdcec8), add an information disclosure button to launch this screen modally.

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
