### ISSUE TITLE
New Add Issuer Flow

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-iOS#17]
The Add issuer flow has been designed to be more like Slack's on-boarding.

[Zeplin link](https://zpl.io/Z2dtJcJ), screenshot below for reference:
<img width="320" alt="screen shot 2016-12-21 at 11 21 05 am" src="https://cloud.githubusercontent.com/assets/547866/21400945/a0143a88-c76f-11e6-8b22-3c9d5e95cceb.png">

Checklist
- [ ] Launched from the existing "Add issuer" action sheet button.
- [ ] Uses Float label pattern
- [ ] Keeps track of the number of steps.
- [ ] On the second screen, inspects the clipboard to auto-paste-and-submit if they copied the one-time-use code.
- [ ] New validation & error state for our custom label

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
