### ISSUE TITLE
Use WebView for pre-v2 certificates

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-iOS#30]
We can drastically simplify the `RenderedCertificateView` if we *always* used the web view to do our rendering. This would amount to us:

* Constructing the html layout that would match our existing v1.1 & v1.2 rendering
* Adding the CSS that would match our existing v1.1 & v1.2 rendering

It should simplify a lot of the complicated constraints that are introduced by having a webview-in-a-scrollview as well.

**Comment by kimdhamilton** [comment]
no longer needed
