### ISSUE TITLE
Text entries with inline variables are not wrapping

### ISSUE THREAD

**Issue by hevyw8** [blockchain-certificates/wallet-iOS#34]
lateral scrolling is enabled but the lack of wrapping is inconsistent w/ android

iOS:

![img_1559](https://user-images.githubusercontent.com/750940/30394560-03df653e-9889-11e7-8f8f-132305784559.PNG)

Android:

![screenshot_20170913-125600](https://user-images.githubusercontent.com/750940/30394661-5ac3e51e-9889-11e7-996d-0dc3257eb8f5.png)

**Comment by hevyw8** [comment]
example cert: https://certificates.learningmachine.com/certificate/6c81c0a9072f5818b323d2b2ca329c44

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
