### ISSUE TITLE
Pressing 'Go' key when entering one-time code in Add Issuer screen does not submit issuer info

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-iOS#35]
1. Launch the wire mock server
2. Go to add issuer.
3. Add one with `http://localhost:1234/issuer/accept` and any one-time code.
4. Tap 'Go' when focused in the one-time code field. 

Expected: It submits the screen & the issuer is added.
Actual: Nothing happens.

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
