### ISSUE TITLE
Show more steps during verification

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-iOS#36]
per @darhontidis, these concrete (abstracted) steps should be shown during verification.

Verification Steps during certificate verification:
```
Computing local hash...
Fetching remote hash...
Comparing local and remote hashes...
Checking merkle root...
Checking receipt...
Checking authenticity...
Checking issuer's signature...
Checking if the certificate has been revoked...
```
result:
```
Verified!
or
Not Verified
```

Also, it'd be good to standardize all our language to use `Verify` and `Verification` rather than `Validate` and `Validation`.

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
