### ISSUE TITLE
Remove 'No subtitle provided' text from cert listing in issuer screen.

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-iOS#38]
If the cert does not have a subtitle provided, we should use a cell display without a subtitle.
![28282456-1dcd7f56-6af0-11e7-8850-325ce75a79ca](https://user-images.githubusercontent.com/547866/30397923-ae1797d6-988b-11e7-8486-59dc5926423b.PNG)

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
