### ISSUE TITLE
Clicking cert link from an issuer that has not been added is unfunctional

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-iOS#41]
From @hevyw8:
> I don't think this is high priority as it will be handled by ownership when implemented
>
> steps to repro:
> 1. add an org to wallet
> 2. click a certificate link from an org that has not been added
>
> expected: error or certificate imports
> actual: app populates but it just shows the orgs screen

**Comment by downie** [comment]
@hevyw8 Do you remember what build this bug was found in? [This test](https://github.com/blockchain-certificates/wallet-iOS/blob/xcode9/certificatesUITests/ExistingIssuerTests.swift#L72) should excite this exact scenario, and it's been passing for 2 weeks.

**Comment by hevyw8** [comment]
@downie I don't have that documented, unfortunately. But I just repro'd in build 101.

**Comment by downie** [comment]
Which certificate were you adding that repro'd it in build 101?

**Comment by downie** [comment]
Or better yet, what was the certificate link that you clicked?

**Comment by hevyw8** [comment]
@downie any link in slack should work as long as you haven't accepted an invite from that particular org

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
