### ISSUE TITLE
cert title misalignment

### ISSUE THREAD

**Issue by hevyw8** [blockchain-certificates/wallet-iOS#52]
iphone 6s plus
iOS version 11.2

red oval highlights misaligned cert

obscured cert content in black box
![img_004c793a3241-1](https://user-images.githubusercontent.com/750940/33450728-62483cc8-d5d2-11e7-8d55-7470a0adcbab.jpeg)

**Comment by downie** [comment]
Do you know what certificate this was in order to repro?

**Comment by hevyw8** [comment]
@downie oh man, I believe it used to be every cert. But it appears that it cleared up. maybe it was a developer beta iOS thing. Feel free to close and I'll reopen w/ an example cert if it recurs.

**Comment by hevyw8** [comment]
@downie It just showed back up

https://certificates.prod-manual-testnet.com/certificate/9b1c2d645867555983d37b3600ac391d

![img_90fe78d8b254-1](https://user-images.githubusercontent.com/750940/35347837-e84cf846-00fb-11e8-99e0-e2a1c0e08d54.jpeg)

I don't think it's cert specific. I think it just happens on initial import. Because when I navigated back to the cert just now, it was aligned correctly.

**Comment by downie** [comment]
Weird! Alright then, lets leave this open.

**Comment by kimdhamilton** [comment]
Fixed with SmallPlanet changes.
