### ISSUE TITLE
Japanese i18n

### ISSUE THREAD

**Issue by akodate** [blockchain-certificates/wallet-iOS#60]
I've finished Japanese i18n for cert-verifier-js (https://github.com/blockchain-certificates/cert-verifier-js/pull/134) and now I'd like to do the same for the Blockcerts wallet. Could someone point me in the right direction on where/how I can do that?

**Comment by AnthonyRonning** [comment]
Hi @akodate, thanks for asking. I had another user asking about how to do it on iOS as well. 

I'll try to get a little readme going for other contributors, but in the meantime, here's some info: 

Our english copy is located here: https://github.com/blockchain-certificates/wallet-iOS/blob/master/wallet/Base.lproj/Localizable.strings

And here's an example of what our spanish translations look like: https://github.com/blockchain-certificates/wallet-iOS/tree/master/wallet/es.lproj


In order to maintain feature parity amongst the apps, take a look at the recent android translations that a user did to get an idea of how you would do so there as well: https://github.com/blockchain-certificates/wallet-android/pull/30/files

**Comment by akodate** [comment]
@AnthonyRonning Great! This might be the info I need to get going.
One more question before I start: if there are no issues with my translations, can I assume they will eventually make it into the Blockcerts Wallet app?

**Comment by AnthonyRonning** [comment]
@akodate yes! Hopefully within a month.

**Comment by AnthonyRonning** [comment]
One last thing, as we get ready for deployment: mind translating the store text? 

---

Blockcerts Wallet is the easiest way to receive and share official credentials from a wide range of institutions, like universities, government agencies, and employers. 

Your credentials are registered on the Bitcoin blockchain, so they can be shared directly and independently verified.

• Take ownership of your own digital credentials
• Share them in a format that is independently verifiable anywhere
• Build a lifelong record across institutions
• Tamper-proof and completely secure

Blockcerts Wallet is part of a larger open source project that was started by M.I.T. in 2016 and continues to grow. More information can be found at www.blockcerts.org. You can learn more about Learning Machine at www.learningmachine.com.

**Comment by akodate** [comment]
Hi @AnthonyRonning 

Sure I'll handle it, hopefully this week.

**Comment by akodate** [comment]
Hey @AnthonyRonning 
I've prepared the translation you wanted.

ブロックサーツウォレット（Blockcerts Wallet）は、大学、行政機関や雇用先など様々な組織が発行する正式な証明書を管理するための最も簡単な方法です。

証明書はビットコインのブロックチェーンで登録されているため、直接シェアすることが可能であり、独自に認証することもできます。

• 自分の証明書を自分で管理する
• どこでも独自に認証することができるフォーマットで証明書をシェアする
• 組織の枠に囚われず、生涯を通じた業績履歴を築く
• 証明書が改ざん不可能で、完全にセキュア
などのメリットがあります。

ブロックサーツウォレットは、2016年にマサチューセッツ工科大学（MIT）で発祥したさらに大規模のオープンソースプロジェクトの一部で、そのプロジェクトはまだまだ成長しています。詳しい情報はwww.blockcerts.orgをご覧ください。Learning Machineに関する情報はwww.learningmachine.comにて確認できます。

**Comment by AnthonyRonning** [comment]
Thank you @akodate! 

Really quick, hopefully last one, can you translate "Independently Verifiable Credentials" ? Looks like each app requires a "short description".

**Comment by akodate** [comment]
Here you are:

独自に認証できる証明書

**Comment by AnthonyRonning** [comment]
Forgot to mention, but Japanese and Italian has been added to both App Stores last month! Thanks a lot for the effort and sorry if it took so long. Should have a good process going forward for additional languages thanks to your efforts.

**Comment by digit-ink** [comment]
That's great to hear! It'll be good to see the new languages in production, and I'm glad I could help out. Let me know if there's anything else I can assist with.

**Comment by akodate** [comment]
That's great to hear! It'll be good to see the new languages in production, and I'm glad I could help out. Let me know if there's anything else I can assist with.
