### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by dariomas** [blockchain-certificates/wallet-iOS#63]
Hi All,
I have just added my PR https://github.com/blockchain-certificates/wallet-iOS/pull/62 with the Italian translation but Travis output some errors unrelated with my commit.
I don have the Apple Dev Tools; I just translated the strings like the "es" files, so please may you check that my files are working with your SDK?

Thank you,
  Dariomas_

**Comment by AnthonyRonning** [comment]
Thanks @dariomas, I will be able to check into it next week, I'm out for the rest of this week. Yeah, I don't think the travis build has ever really worked for iOS. But it does look like it's working again for android, so I'll double check that one too. I was waiting on feature parity amongst both android/iOS before merging one or the other in, so I appreciate you doing both.

**Comment by AnthonyRonning** [comment]
One last thing, as we get ready for deployment: mind translating the store text?

---

Blockcerts Wallet is the easiest way to receive and share official credentials from a wide range of institutions, like universities, government agencies, and employers.

Your credentials are registered on the Bitcoin blockchain, so they can be shared directly and independently verified.

• Take ownership of your own digital credentials
• Share them in a format that is independently verifiable anywhere
• Build a lifelong record across institutions
• Tamper-proof and completely secure

Blockcerts Wallet is part of a larger open source project that was started by M.I.T. in 2016 and continues to grow. More information can be found at www.blockcerts.org. You can learn more about Learning Machine at www.learningmachine.com.

**Comment by dariomas** [comment]
Hi @AnthonyRonning ,
I'll work on it as soon as possible.

**Comment by AnthonyRonning** [comment]
@dariomas 

Also, there is a "short description" that we could use some help translating as well: 

"Independently Verifiable Credentials"

Thank you.

**Comment by dariomas** [comment]
Hi @AnthonyRonning ,
following my Italian translation for the store text:

"Blockcerts Wallet è il modo più semplice per ricevere e condividere certificazioni ufficiali di qualifiche da una vasta gamma di enti, come università, agenzie governative e datori di lavoro.

Le tue qualifiche sono registrate sulla blockchain Bitcoin, quindi possono essere condivise direttamente e verificate in modo indipendente.

• Assumi la proprietà delle tue qualifiche digitali
• Condividile in un formato ovunque verificabile in modo indipendente
• Costruisci un registro dei conseguimenti da tutti gli enti, per tutta la vita
• A prova di manomissione e completamente sicuro

Blockcerts Wallet fa parte di un più ampio progetto open source avviato dal M.I.T. nel 2016 e che continua a crescere. Ulteriori informazioni sono disponibili all'indirizzo www.blockcerts.org. Puoi saperne di più su Learning Machine visitando www.learningmachine.com."


Also, the "short description":

"Certificazioni verificabili in modo indipendente"

Thank you_

**Comment by AnthonyRonning** [comment]
Forgot to mention, but Japanese and Italian has been added to both App Stores last month! Thanks a lot for the effort and sorry if it took so long. Should have a good process going forward for additional languages thanks to your efforts.
