### ISSUE TITLE
support for blockcert v3

### ISSUE THREAD

**Issue by 6eer** [blockchain-certificates/wallet-iOS#76]
Hi, 

Are you working on or planning to add support to blockcerts v3? 

Thanks,
6eer.

**Comment by raiseandfall** [comment]
Hi @6eer, thanks for your interest. We are in the process to add Blockcerts v3 support to both iOS & Android apps.

**Comment by raiseandfall** [comment]
@6eer well, this took a while but support for Blockcerts V3 has been finally released in the App Store today.
