### ISSUE TITLE
are there any alternatives to the app ? 

### ISSUE THREAD

**Issue by TrevCan** [blockchain-certificates/wallet-iOS#78]
Hello, I'm required to download this application onto my phone to get a digital certificate from my university.

But to be honest, the iOS App Store reviews do not seem promising. Plus, I've tried contacting my university if there are other alternatives or on which tech this is based but they haven't replied back.

My main question is:
** Can I issue / get my certificate without a mobile phone ? **

How can I verify my certificate without using iOS / Android?

Can I get this to work (verification and issuing) through a *NIX system ? 

Is there a CLI I could use ?

Thanks for the info.

**Comment by raiseandfall** [comment]
Hi @TrevCan 

You could store your certificates anywhere, and use other alternatives to verify/view them:
- The `Blockcerts Verifier` component, which is hosted here: https://www.blockcerts.org/
- you could also run the [Blockcerts Verifier](https://github.com/blockchain-certificates/blockcerts-verifier) on your own, the code source is here: 
- while we do not have a CLI for verification, you can look into [cert-verifier-js](https://github.com/blockchain-certificates/cert-verifier-js):  which is essentially a JS library to verify Blockcerts documents. 
- there is also a [Python library for verification](https://github.com/blockchain-certificates/cert-verifier), but I've never worked on it and I'm not familiar with its current state. You can ask for more info there

**Comment by TrevCan** [comment]
Hello there. Thanks for your response. Based on my university's comments my guess was that it would be linked to my phone's private key or something like that. But it does not seem like it, as I have been able to verify the certificates from other devices.

Thanks

**Comment by raiseandfall** [comment]
Your private key is indeed stored on your phone, but the location of the private key doesn't define how to verify a Blockcerts document.
The verification process establishes the veracity of several aspects of a Blockcerts document, but it never needs your private key. 
The blockchain technology allows anybody to verify a Blockcerts from anywhere, instantly and for free.
